# Generated by Django 5.0.3 on 2024-03-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_code', models.TextField(primary_key=True, serialize=False)),
                ('country_name', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
    ]
